"""empty message

Revision ID: 45d052037974
Revises: f12732388b58
Create Date: 2021-08-19 10:04:17.106390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d052037974'
down_revision = 'f12732388b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'available_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('available_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
