"""empty message

Revision ID: 5a072cdb333b
Revises: 6a407608ddb3
Create Date: 2021-05-11 12:53:32.041128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a072cdb333b'
down_revision = '6a407608ddb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('videos', sa.Column('total_inventory', sa.Integer(), nullable=True))
    op.drop_column('videos', 'name')
    op.drop_column('videos', 'postal_code')
    op.drop_column('videos', 'registered_at')
    op.drop_column('videos', 'phone')
    op.drop_column('videos', 'videos_checked_out_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('postal_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('videos', 'total_inventory')
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'release_date')
    # ### end Alembic commands ###
