"""empty message

Revision ID: f6f184bf46ec
Revises: 5a072cdb333b
Create Date: 2021-05-11 13:39:22.477906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f184bf46ec'
down_revision = '5a072cdb333b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'available_inventory')
    # ### end Alembic commands ###
