"""empty message

Revision ID: ff575a69983e
Revises: 90e270679a07
Create Date: 2021-05-12 19:39:24.993905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff575a69983e'
down_revision = '90e270679a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'status')
    # ### end Alembic commands ###
